apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesail-gateway-two
spec:
  template:
    spec:
      containers:
        - name: kubesail-gateway
          env:
            - name: KUBESAIL_API_TARGET
              value: api
            - name: GATEWAY_ADDRESSES
              value: dev-two.k8g8.com,dev-two.kubegateway.com
            - name: REDIS_SERVERS
              value: kubesail-gateway-two-redis:6379
