compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

enableTransparentWorkspaces: false

immutablePatterns:
  - .pnp.*

logFilters:
  - code: YN0005
    level: discard

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.0.2.cjs
