apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
    - image: kubesail/agent
      context: .
      sync:
        manual:
          - src: lib/**/*
            dest: .
          - src: test/**/*
            dest: .
    - image: kubesail/gateway
      context: .
      sync:
        manual:
          - src: lib/**/*
            dest: .
          - src: test/**/*
            dest: .
      docker:
        dockerfile: Dockerfile
manifests:
  kustomize:
    paths:
      - k8s/overlays/dev/agent
      - k8s/overlays/dev/gateway
