apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
    - image: kubesail/agent
      context: .
      sync:
        manual:
          - src: lib/**/*
            dest: .
          - src: test/**/*
            dest: .
      docker:
        dockerfile: Dockerfile
deploy:
  kustomize:
    paths:
      - k8s/overlays/dev
