// flow-typed signature: 23a604af11c257ac1544d3577781867d
// flow-typed version: <<STUB>>/http-headers_v^3.0.2/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-headers'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-headers' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'http-headers/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'http-headers/index' {
  declare module.exports: $Exports<'http-headers'>;
}
declare module 'http-headers/index.js' {
  declare module.exports: $Exports<'http-headers'>;
}
declare module 'http-headers/test.js' {
  declare module.exports: $Exports<'http-headers/test'>;
}
