// flow-typed signature: a475492f4684506889b3aba8f2faa7f6
// flow-typed version: <<STUB>>/kubernetes-client_v^8.3.6/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kubernetes-client'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'kubernetes-client' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kubernetes-client/backends/kubernetes-client-node' {
  declare module.exports: any;
}

declare module 'kubernetes-client/backends/request/auth-providers/cmd' {
  declare module.exports: any;
}

declare module 'kubernetes-client/backends/request/auth-providers/openid' {
  declare module.exports: any;
}

declare module 'kubernetes-client/backends/request/client' {
  declare module.exports: any;
}

declare module 'kubernetes-client/backends/request/config' {
  declare module.exports: any;
}

declare module 'kubernetes-client/backends/request' {
  declare module.exports: any;
}

declare module 'kubernetes-client/lib/alias' {
  declare module.exports: any;
}

declare module 'kubernetes-client/lib/config' {
  declare module.exports: any;
}

declare module 'kubernetes-client/lib' {
  declare module.exports: any;
}

declare module 'kubernetes-client/lib/swagger-client' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kubernetes-client/backends/kubernetes-client-node.js' {
  declare module.exports: $Exports<'kubernetes-client/backends/kubernetes-client-node'>;
}
declare module 'kubernetes-client/backends/request/auth-providers/cmd.js' {
  declare module.exports: $Exports<'kubernetes-client/backends/request/auth-providers/cmd'>;
}
declare module 'kubernetes-client/backends/request/auth-providers/openid.js' {
  declare module.exports: $Exports<'kubernetes-client/backends/request/auth-providers/openid'>;
}
declare module 'kubernetes-client/backends/request/client.js' {
  declare module.exports: $Exports<'kubernetes-client/backends/request/client'>;
}
declare module 'kubernetes-client/backends/request/config.js' {
  declare module.exports: $Exports<'kubernetes-client/backends/request/config'>;
}
declare module 'kubernetes-client/backends/request/index' {
  declare module.exports: $Exports<'kubernetes-client/backends/request'>;
}
declare module 'kubernetes-client/backends/request/index.js' {
  declare module.exports: $Exports<'kubernetes-client/backends/request'>;
}
declare module 'kubernetes-client/lib/alias.js' {
  declare module.exports: $Exports<'kubernetes-client/lib/alias'>;
}
declare module 'kubernetes-client/lib/config.js' {
  declare module.exports: $Exports<'kubernetes-client/lib/config'>;
}
declare module 'kubernetes-client/lib/index' {
  declare module.exports: $Exports<'kubernetes-client/lib'>;
}
declare module 'kubernetes-client/lib/index.js' {
  declare module.exports: $Exports<'kubernetes-client/lib'>;
}
declare module 'kubernetes-client/lib/swagger-client.js' {
  declare module.exports: $Exports<'kubernetes-client/lib/swagger-client'>;
}
