// flow-typed signature: f051cc3e8fe3d73bb0c5c9db4873633a
// flow-typed version: <<STUB>>/sni_v^1.0.0/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sni'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sni' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sni/bench' {
  declare module.exports: any;
}

declare module 'sni/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sni/bench.js' {
  declare module.exports: $Exports<'sni/bench'>;
}
declare module 'sni/index' {
  declare module.exports: $Exports<'sni'>;
}
declare module 'sni/index.js' {
  declare module.exports: $Exports<'sni'>;
}
declare module 'sni/test.js' {
  declare module.exports: $Exports<'sni/test'>;
}
