// flow-typed signature: 884440488a5c3273fded1ef1eb306919
// flow-typed version: <<STUB>>/socket.io-stream_v^0.9.1/flow_v0.120.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'socket.io-stream'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'socket.io-stream' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'socket.io-stream/lib/blob-read-stream' {
  declare module.exports: any;
}

declare module 'socket.io-stream/lib' {
  declare module.exports: any;
}

declare module 'socket.io-stream/lib/iostream' {
  declare module.exports: any;
}

declare module 'socket.io-stream/lib/parser' {
  declare module.exports: any;
}

declare module 'socket.io-stream/lib/socket' {
  declare module.exports: any;
}

declare module 'socket.io-stream/lib/uuid' {
  declare module.exports: any;
}

declare module 'socket.io-stream/socket.io-stream' {
  declare module.exports: any;
}

// Filename aliases
declare module 'socket.io-stream/index' {
  declare module.exports: $Exports<'socket.io-stream'>;
}
declare module 'socket.io-stream/index.js' {
  declare module.exports: $Exports<'socket.io-stream'>;
}
declare module 'socket.io-stream/lib/blob-read-stream.js' {
  declare module.exports: $Exports<'socket.io-stream/lib/blob-read-stream'>;
}
declare module 'socket.io-stream/lib/index' {
  declare module.exports: $Exports<'socket.io-stream/lib'>;
}
declare module 'socket.io-stream/lib/index.js' {
  declare module.exports: $Exports<'socket.io-stream/lib'>;
}
declare module 'socket.io-stream/lib/iostream.js' {
  declare module.exports: $Exports<'socket.io-stream/lib/iostream'>;
}
declare module 'socket.io-stream/lib/parser.js' {
  declare module.exports: $Exports<'socket.io-stream/lib/parser'>;
}
declare module 'socket.io-stream/lib/socket.js' {
  declare module.exports: $Exports<'socket.io-stream/lib/socket'>;
}
declare module 'socket.io-stream/lib/uuid.js' {
  declare module.exports: $Exports<'socket.io-stream/lib/uuid'>;
}
declare module 'socket.io-stream/socket.io-stream.js' {
  declare module.exports: $Exports<'socket.io-stream/socket.io-stream'>;
}
