// flow-typed signature: 77c1b50e75919fef50b45e92b32174dc
// flow-typed version: <<STUB>>/socket.io-redis_v^5.2.0/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'socket.io-redis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'socket.io-redis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'socket.io-redis/index' {
  declare module.exports: $Exports<'socket.io-redis'>;
}
declare module 'socket.io-redis/index.js' {
  declare module.exports: $Exports<'socket.io-redis'>;
}
