// flow-typed signature: abc0cc4a224213f58780c0b4658f0435
// flow-typed version: <<STUB>>/validator_v^12.1.0/flow_v0.115.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'validator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'validator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'validator/es' {
  declare module.exports: any;
}

declare module 'validator/es/lib/alpha' {
  declare module.exports: any;
}

declare module 'validator/es/lib/blacklist' {
  declare module.exports: any;
}

declare module 'validator/es/lib/contains' {
  declare module.exports: any;
}

declare module 'validator/es/lib/equals' {
  declare module.exports: any;
}

declare module 'validator/es/lib/escape' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isAfter' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isAlpha' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isAlphanumeric' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isAscii' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isBase32' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isBase64' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isBefore' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isBIC' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isBoolean' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isByteLength' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isCreditCard' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isCurrency' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isDataURI' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isDecimal' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isDivisibleBy' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isEmail' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isEmpty' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isFloat' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isFQDN' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isFullWidth' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isHalfWidth' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isHash' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isHexadecimal' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isHexColor' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isIdentityCard' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isIn' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isInt' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isIP' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isIPRange' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isISBN' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isISIN' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isISO31661Alpha2' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isISO31661Alpha3' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isISO8601' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isISRC' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isISSN' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isJSON' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isJWT' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isLatLong' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isLength' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isLowercase' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isMACAddress' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isMagnetURI' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isMD5' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isMimeType' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isMobilePhone' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isMongoId' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isMultibyte' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isNumeric' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isOctal' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isPort' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isPostalCode' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isRFC3339' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isSlug' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isSurrogatePair' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isUppercase' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isURL' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isUUID' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isVariableWidth' {
  declare module.exports: any;
}

declare module 'validator/es/lib/isWhitelisted' {
  declare module.exports: any;
}

declare module 'validator/es/lib/ltrim' {
  declare module.exports: any;
}

declare module 'validator/es/lib/matches' {
  declare module.exports: any;
}

declare module 'validator/es/lib/normalizeEmail' {
  declare module.exports: any;
}

declare module 'validator/es/lib/rtrim' {
  declare module.exports: any;
}

declare module 'validator/es/lib/stripLow' {
  declare module.exports: any;
}

declare module 'validator/es/lib/toBoolean' {
  declare module.exports: any;
}

declare module 'validator/es/lib/toDate' {
  declare module.exports: any;
}

declare module 'validator/es/lib/toFloat' {
  declare module.exports: any;
}

declare module 'validator/es/lib/toInt' {
  declare module.exports: any;
}

declare module 'validator/es/lib/trim' {
  declare module.exports: any;
}

declare module 'validator/es/lib/unescape' {
  declare module.exports: any;
}

declare module 'validator/es/lib/util/assertString' {
  declare module.exports: any;
}

declare module 'validator/es/lib/util/includes' {
  declare module.exports: any;
}

declare module 'validator/es/lib/util/merge' {
  declare module.exports: any;
}

declare module 'validator/es/lib/util/toString' {
  declare module.exports: any;
}

declare module 'validator/es/lib/whitelist' {
  declare module.exports: any;
}

declare module 'validator/lib/alpha' {
  declare module.exports: any;
}

declare module 'validator/lib/blacklist' {
  declare module.exports: any;
}

declare module 'validator/lib/contains' {
  declare module.exports: any;
}

declare module 'validator/lib/equals' {
  declare module.exports: any;
}

declare module 'validator/lib/escape' {
  declare module.exports: any;
}

declare module 'validator/lib/isAfter' {
  declare module.exports: any;
}

declare module 'validator/lib/isAlpha' {
  declare module.exports: any;
}

declare module 'validator/lib/isAlphanumeric' {
  declare module.exports: any;
}

declare module 'validator/lib/isAscii' {
  declare module.exports: any;
}

declare module 'validator/lib/isBase32' {
  declare module.exports: any;
}

declare module 'validator/lib/isBase64' {
  declare module.exports: any;
}

declare module 'validator/lib/isBefore' {
  declare module.exports: any;
}

declare module 'validator/lib/isBIC' {
  declare module.exports: any;
}

declare module 'validator/lib/isBoolean' {
  declare module.exports: any;
}

declare module 'validator/lib/isByteLength' {
  declare module.exports: any;
}

declare module 'validator/lib/isCreditCard' {
  declare module.exports: any;
}

declare module 'validator/lib/isCurrency' {
  declare module.exports: any;
}

declare module 'validator/lib/isDataURI' {
  declare module.exports: any;
}

declare module 'validator/lib/isDecimal' {
  declare module.exports: any;
}

declare module 'validator/lib/isDivisibleBy' {
  declare module.exports: any;
}

declare module 'validator/lib/isEmail' {
  declare module.exports: any;
}

declare module 'validator/lib/isEmpty' {
  declare module.exports: any;
}

declare module 'validator/lib/isFloat' {
  declare module.exports: any;
}

declare module 'validator/lib/isFQDN' {
  declare module.exports: any;
}

declare module 'validator/lib/isFullWidth' {
  declare module.exports: any;
}

declare module 'validator/lib/isHalfWidth' {
  declare module.exports: any;
}

declare module 'validator/lib/isHash' {
  declare module.exports: any;
}

declare module 'validator/lib/isHexadecimal' {
  declare module.exports: any;
}

declare module 'validator/lib/isHexColor' {
  declare module.exports: any;
}

declare module 'validator/lib/isIdentityCard' {
  declare module.exports: any;
}

declare module 'validator/lib/isIn' {
  declare module.exports: any;
}

declare module 'validator/lib/isInt' {
  declare module.exports: any;
}

declare module 'validator/lib/isIP' {
  declare module.exports: any;
}

declare module 'validator/lib/isIPRange' {
  declare module.exports: any;
}

declare module 'validator/lib/isISBN' {
  declare module.exports: any;
}

declare module 'validator/lib/isISIN' {
  declare module.exports: any;
}

declare module 'validator/lib/isISO31661Alpha2' {
  declare module.exports: any;
}

declare module 'validator/lib/isISO31661Alpha3' {
  declare module.exports: any;
}

declare module 'validator/lib/isISO8601' {
  declare module.exports: any;
}

declare module 'validator/lib/isISRC' {
  declare module.exports: any;
}

declare module 'validator/lib/isISSN' {
  declare module.exports: any;
}

declare module 'validator/lib/isJSON' {
  declare module.exports: any;
}

declare module 'validator/lib/isJWT' {
  declare module.exports: any;
}

declare module 'validator/lib/isLatLong' {
  declare module.exports: any;
}

declare module 'validator/lib/isLength' {
  declare module.exports: any;
}

declare module 'validator/lib/isLowercase' {
  declare module.exports: any;
}

declare module 'validator/lib/isMACAddress' {
  declare module.exports: any;
}

declare module 'validator/lib/isMagnetURI' {
  declare module.exports: any;
}

declare module 'validator/lib/isMD5' {
  declare module.exports: any;
}

declare module 'validator/lib/isMimeType' {
  declare module.exports: any;
}

declare module 'validator/lib/isMobilePhone' {
  declare module.exports: any;
}

declare module 'validator/lib/isMongoId' {
  declare module.exports: any;
}

declare module 'validator/lib/isMultibyte' {
  declare module.exports: any;
}

declare module 'validator/lib/isNumeric' {
  declare module.exports: any;
}

declare module 'validator/lib/isOctal' {
  declare module.exports: any;
}

declare module 'validator/lib/isPort' {
  declare module.exports: any;
}

declare module 'validator/lib/isPostalCode' {
  declare module.exports: any;
}

declare module 'validator/lib/isRFC3339' {
  declare module.exports: any;
}

declare module 'validator/lib/isSlug' {
  declare module.exports: any;
}

declare module 'validator/lib/isSurrogatePair' {
  declare module.exports: any;
}

declare module 'validator/lib/isUppercase' {
  declare module.exports: any;
}

declare module 'validator/lib/isURL' {
  declare module.exports: any;
}

declare module 'validator/lib/isUUID' {
  declare module.exports: any;
}

declare module 'validator/lib/isVariableWidth' {
  declare module.exports: any;
}

declare module 'validator/lib/isWhitelisted' {
  declare module.exports: any;
}

declare module 'validator/lib/ltrim' {
  declare module.exports: any;
}

declare module 'validator/lib/matches' {
  declare module.exports: any;
}

declare module 'validator/lib/normalizeEmail' {
  declare module.exports: any;
}

declare module 'validator/lib/rtrim' {
  declare module.exports: any;
}

declare module 'validator/lib/stripLow' {
  declare module.exports: any;
}

declare module 'validator/lib/toBoolean' {
  declare module.exports: any;
}

declare module 'validator/lib/toDate' {
  declare module.exports: any;
}

declare module 'validator/lib/toFloat' {
  declare module.exports: any;
}

declare module 'validator/lib/toInt' {
  declare module.exports: any;
}

declare module 'validator/lib/trim' {
  declare module.exports: any;
}

declare module 'validator/lib/unescape' {
  declare module.exports: any;
}

declare module 'validator/lib/util/assertString' {
  declare module.exports: any;
}

declare module 'validator/lib/util/includes' {
  declare module.exports: any;
}

declare module 'validator/lib/util/merge' {
  declare module.exports: any;
}

declare module 'validator/lib/util/toString' {
  declare module.exports: any;
}

declare module 'validator/lib/whitelist' {
  declare module.exports: any;
}

declare module 'validator/validator' {
  declare module.exports: any;
}

declare module 'validator/validator.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'validator/es/index' {
  declare module.exports: $Exports<'validator/es'>;
}
declare module 'validator/es/index.js' {
  declare module.exports: $Exports<'validator/es'>;
}
declare module 'validator/es/lib/alpha.js' {
  declare module.exports: $Exports<'validator/es/lib/alpha'>;
}
declare module 'validator/es/lib/blacklist.js' {
  declare module.exports: $Exports<'validator/es/lib/blacklist'>;
}
declare module 'validator/es/lib/contains.js' {
  declare module.exports: $Exports<'validator/es/lib/contains'>;
}
declare module 'validator/es/lib/equals.js' {
  declare module.exports: $Exports<'validator/es/lib/equals'>;
}
declare module 'validator/es/lib/escape.js' {
  declare module.exports: $Exports<'validator/es/lib/escape'>;
}
declare module 'validator/es/lib/isAfter.js' {
  declare module.exports: $Exports<'validator/es/lib/isAfter'>;
}
declare module 'validator/es/lib/isAlpha.js' {
  declare module.exports: $Exports<'validator/es/lib/isAlpha'>;
}
declare module 'validator/es/lib/isAlphanumeric.js' {
  declare module.exports: $Exports<'validator/es/lib/isAlphanumeric'>;
}
declare module 'validator/es/lib/isAscii.js' {
  declare module.exports: $Exports<'validator/es/lib/isAscii'>;
}
declare module 'validator/es/lib/isBase32.js' {
  declare module.exports: $Exports<'validator/es/lib/isBase32'>;
}
declare module 'validator/es/lib/isBase64.js' {
  declare module.exports: $Exports<'validator/es/lib/isBase64'>;
}
declare module 'validator/es/lib/isBefore.js' {
  declare module.exports: $Exports<'validator/es/lib/isBefore'>;
}
declare module 'validator/es/lib/isBIC.js' {
  declare module.exports: $Exports<'validator/es/lib/isBIC'>;
}
declare module 'validator/es/lib/isBoolean.js' {
  declare module.exports: $Exports<'validator/es/lib/isBoolean'>;
}
declare module 'validator/es/lib/isByteLength.js' {
  declare module.exports: $Exports<'validator/es/lib/isByteLength'>;
}
declare module 'validator/es/lib/isCreditCard.js' {
  declare module.exports: $Exports<'validator/es/lib/isCreditCard'>;
}
declare module 'validator/es/lib/isCurrency.js' {
  declare module.exports: $Exports<'validator/es/lib/isCurrency'>;
}
declare module 'validator/es/lib/isDataURI.js' {
  declare module.exports: $Exports<'validator/es/lib/isDataURI'>;
}
declare module 'validator/es/lib/isDecimal.js' {
  declare module.exports: $Exports<'validator/es/lib/isDecimal'>;
}
declare module 'validator/es/lib/isDivisibleBy.js' {
  declare module.exports: $Exports<'validator/es/lib/isDivisibleBy'>;
}
declare module 'validator/es/lib/isEmail.js' {
  declare module.exports: $Exports<'validator/es/lib/isEmail'>;
}
declare module 'validator/es/lib/isEmpty.js' {
  declare module.exports: $Exports<'validator/es/lib/isEmpty'>;
}
declare module 'validator/es/lib/isFloat.js' {
  declare module.exports: $Exports<'validator/es/lib/isFloat'>;
}
declare module 'validator/es/lib/isFQDN.js' {
  declare module.exports: $Exports<'validator/es/lib/isFQDN'>;
}
declare module 'validator/es/lib/isFullWidth.js' {
  declare module.exports: $Exports<'validator/es/lib/isFullWidth'>;
}
declare module 'validator/es/lib/isHalfWidth.js' {
  declare module.exports: $Exports<'validator/es/lib/isHalfWidth'>;
}
declare module 'validator/es/lib/isHash.js' {
  declare module.exports: $Exports<'validator/es/lib/isHash'>;
}
declare module 'validator/es/lib/isHexadecimal.js' {
  declare module.exports: $Exports<'validator/es/lib/isHexadecimal'>;
}
declare module 'validator/es/lib/isHexColor.js' {
  declare module.exports: $Exports<'validator/es/lib/isHexColor'>;
}
declare module 'validator/es/lib/isIdentityCard.js' {
  declare module.exports: $Exports<'validator/es/lib/isIdentityCard'>;
}
declare module 'validator/es/lib/isIn.js' {
  declare module.exports: $Exports<'validator/es/lib/isIn'>;
}
declare module 'validator/es/lib/isInt.js' {
  declare module.exports: $Exports<'validator/es/lib/isInt'>;
}
declare module 'validator/es/lib/isIP.js' {
  declare module.exports: $Exports<'validator/es/lib/isIP'>;
}
declare module 'validator/es/lib/isIPRange.js' {
  declare module.exports: $Exports<'validator/es/lib/isIPRange'>;
}
declare module 'validator/es/lib/isISBN.js' {
  declare module.exports: $Exports<'validator/es/lib/isISBN'>;
}
declare module 'validator/es/lib/isISIN.js' {
  declare module.exports: $Exports<'validator/es/lib/isISIN'>;
}
declare module 'validator/es/lib/isISO31661Alpha2.js' {
  declare module.exports: $Exports<'validator/es/lib/isISO31661Alpha2'>;
}
declare module 'validator/es/lib/isISO31661Alpha3.js' {
  declare module.exports: $Exports<'validator/es/lib/isISO31661Alpha3'>;
}
declare module 'validator/es/lib/isISO8601.js' {
  declare module.exports: $Exports<'validator/es/lib/isISO8601'>;
}
declare module 'validator/es/lib/isISRC.js' {
  declare module.exports: $Exports<'validator/es/lib/isISRC'>;
}
declare module 'validator/es/lib/isISSN.js' {
  declare module.exports: $Exports<'validator/es/lib/isISSN'>;
}
declare module 'validator/es/lib/isJSON.js' {
  declare module.exports: $Exports<'validator/es/lib/isJSON'>;
}
declare module 'validator/es/lib/isJWT.js' {
  declare module.exports: $Exports<'validator/es/lib/isJWT'>;
}
declare module 'validator/es/lib/isLatLong.js' {
  declare module.exports: $Exports<'validator/es/lib/isLatLong'>;
}
declare module 'validator/es/lib/isLength.js' {
  declare module.exports: $Exports<'validator/es/lib/isLength'>;
}
declare module 'validator/es/lib/isLowercase.js' {
  declare module.exports: $Exports<'validator/es/lib/isLowercase'>;
}
declare module 'validator/es/lib/isMACAddress.js' {
  declare module.exports: $Exports<'validator/es/lib/isMACAddress'>;
}
declare module 'validator/es/lib/isMagnetURI.js' {
  declare module.exports: $Exports<'validator/es/lib/isMagnetURI'>;
}
declare module 'validator/es/lib/isMD5.js' {
  declare module.exports: $Exports<'validator/es/lib/isMD5'>;
}
declare module 'validator/es/lib/isMimeType.js' {
  declare module.exports: $Exports<'validator/es/lib/isMimeType'>;
}
declare module 'validator/es/lib/isMobilePhone.js' {
  declare module.exports: $Exports<'validator/es/lib/isMobilePhone'>;
}
declare module 'validator/es/lib/isMongoId.js' {
  declare module.exports: $Exports<'validator/es/lib/isMongoId'>;
}
declare module 'validator/es/lib/isMultibyte.js' {
  declare module.exports: $Exports<'validator/es/lib/isMultibyte'>;
}
declare module 'validator/es/lib/isNumeric.js' {
  declare module.exports: $Exports<'validator/es/lib/isNumeric'>;
}
declare module 'validator/es/lib/isOctal.js' {
  declare module.exports: $Exports<'validator/es/lib/isOctal'>;
}
declare module 'validator/es/lib/isPort.js' {
  declare module.exports: $Exports<'validator/es/lib/isPort'>;
}
declare module 'validator/es/lib/isPostalCode.js' {
  declare module.exports: $Exports<'validator/es/lib/isPostalCode'>;
}
declare module 'validator/es/lib/isRFC3339.js' {
  declare module.exports: $Exports<'validator/es/lib/isRFC3339'>;
}
declare module 'validator/es/lib/isSlug.js' {
  declare module.exports: $Exports<'validator/es/lib/isSlug'>;
}
declare module 'validator/es/lib/isSurrogatePair.js' {
  declare module.exports: $Exports<'validator/es/lib/isSurrogatePair'>;
}
declare module 'validator/es/lib/isUppercase.js' {
  declare module.exports: $Exports<'validator/es/lib/isUppercase'>;
}
declare module 'validator/es/lib/isURL.js' {
  declare module.exports: $Exports<'validator/es/lib/isURL'>;
}
declare module 'validator/es/lib/isUUID.js' {
  declare module.exports: $Exports<'validator/es/lib/isUUID'>;
}
declare module 'validator/es/lib/isVariableWidth.js' {
  declare module.exports: $Exports<'validator/es/lib/isVariableWidth'>;
}
declare module 'validator/es/lib/isWhitelisted.js' {
  declare module.exports: $Exports<'validator/es/lib/isWhitelisted'>;
}
declare module 'validator/es/lib/ltrim.js' {
  declare module.exports: $Exports<'validator/es/lib/ltrim'>;
}
declare module 'validator/es/lib/matches.js' {
  declare module.exports: $Exports<'validator/es/lib/matches'>;
}
declare module 'validator/es/lib/normalizeEmail.js' {
  declare module.exports: $Exports<'validator/es/lib/normalizeEmail'>;
}
declare module 'validator/es/lib/rtrim.js' {
  declare module.exports: $Exports<'validator/es/lib/rtrim'>;
}
declare module 'validator/es/lib/stripLow.js' {
  declare module.exports: $Exports<'validator/es/lib/stripLow'>;
}
declare module 'validator/es/lib/toBoolean.js' {
  declare module.exports: $Exports<'validator/es/lib/toBoolean'>;
}
declare module 'validator/es/lib/toDate.js' {
  declare module.exports: $Exports<'validator/es/lib/toDate'>;
}
declare module 'validator/es/lib/toFloat.js' {
  declare module.exports: $Exports<'validator/es/lib/toFloat'>;
}
declare module 'validator/es/lib/toInt.js' {
  declare module.exports: $Exports<'validator/es/lib/toInt'>;
}
declare module 'validator/es/lib/trim.js' {
  declare module.exports: $Exports<'validator/es/lib/trim'>;
}
declare module 'validator/es/lib/unescape.js' {
  declare module.exports: $Exports<'validator/es/lib/unescape'>;
}
declare module 'validator/es/lib/util/assertString.js' {
  declare module.exports: $Exports<'validator/es/lib/util/assertString'>;
}
declare module 'validator/es/lib/util/includes.js' {
  declare module.exports: $Exports<'validator/es/lib/util/includes'>;
}
declare module 'validator/es/lib/util/merge.js' {
  declare module.exports: $Exports<'validator/es/lib/util/merge'>;
}
declare module 'validator/es/lib/util/toString.js' {
  declare module.exports: $Exports<'validator/es/lib/util/toString'>;
}
declare module 'validator/es/lib/whitelist.js' {
  declare module.exports: $Exports<'validator/es/lib/whitelist'>;
}
declare module 'validator/index' {
  declare module.exports: $Exports<'validator'>;
}
declare module 'validator/index.js' {
  declare module.exports: $Exports<'validator'>;
}
declare module 'validator/lib/alpha.js' {
  declare module.exports: $Exports<'validator/lib/alpha'>;
}
declare module 'validator/lib/blacklist.js' {
  declare module.exports: $Exports<'validator/lib/blacklist'>;
}
declare module 'validator/lib/contains.js' {
  declare module.exports: $Exports<'validator/lib/contains'>;
}
declare module 'validator/lib/equals.js' {
  declare module.exports: $Exports<'validator/lib/equals'>;
}
declare module 'validator/lib/escape.js' {
  declare module.exports: $Exports<'validator/lib/escape'>;
}
declare module 'validator/lib/isAfter.js' {
  declare module.exports: $Exports<'validator/lib/isAfter'>;
}
declare module 'validator/lib/isAlpha.js' {
  declare module.exports: $Exports<'validator/lib/isAlpha'>;
}
declare module 'validator/lib/isAlphanumeric.js' {
  declare module.exports: $Exports<'validator/lib/isAlphanumeric'>;
}
declare module 'validator/lib/isAscii.js' {
  declare module.exports: $Exports<'validator/lib/isAscii'>;
}
declare module 'validator/lib/isBase32.js' {
  declare module.exports: $Exports<'validator/lib/isBase32'>;
}
declare module 'validator/lib/isBase64.js' {
  declare module.exports: $Exports<'validator/lib/isBase64'>;
}
declare module 'validator/lib/isBefore.js' {
  declare module.exports: $Exports<'validator/lib/isBefore'>;
}
declare module 'validator/lib/isBIC.js' {
  declare module.exports: $Exports<'validator/lib/isBIC'>;
}
declare module 'validator/lib/isBoolean.js' {
  declare module.exports: $Exports<'validator/lib/isBoolean'>;
}
declare module 'validator/lib/isByteLength.js' {
  declare module.exports: $Exports<'validator/lib/isByteLength'>;
}
declare module 'validator/lib/isCreditCard.js' {
  declare module.exports: $Exports<'validator/lib/isCreditCard'>;
}
declare module 'validator/lib/isCurrency.js' {
  declare module.exports: $Exports<'validator/lib/isCurrency'>;
}
declare module 'validator/lib/isDataURI.js' {
  declare module.exports: $Exports<'validator/lib/isDataURI'>;
}
declare module 'validator/lib/isDecimal.js' {
  declare module.exports: $Exports<'validator/lib/isDecimal'>;
}
declare module 'validator/lib/isDivisibleBy.js' {
  declare module.exports: $Exports<'validator/lib/isDivisibleBy'>;
}
declare module 'validator/lib/isEmail.js' {
  declare module.exports: $Exports<'validator/lib/isEmail'>;
}
declare module 'validator/lib/isEmpty.js' {
  declare module.exports: $Exports<'validator/lib/isEmpty'>;
}
declare module 'validator/lib/isFloat.js' {
  declare module.exports: $Exports<'validator/lib/isFloat'>;
}
declare module 'validator/lib/isFQDN.js' {
  declare module.exports: $Exports<'validator/lib/isFQDN'>;
}
declare module 'validator/lib/isFullWidth.js' {
  declare module.exports: $Exports<'validator/lib/isFullWidth'>;
}
declare module 'validator/lib/isHalfWidth.js' {
  declare module.exports: $Exports<'validator/lib/isHalfWidth'>;
}
declare module 'validator/lib/isHash.js' {
  declare module.exports: $Exports<'validator/lib/isHash'>;
}
declare module 'validator/lib/isHexadecimal.js' {
  declare module.exports: $Exports<'validator/lib/isHexadecimal'>;
}
declare module 'validator/lib/isHexColor.js' {
  declare module.exports: $Exports<'validator/lib/isHexColor'>;
}
declare module 'validator/lib/isIdentityCard.js' {
  declare module.exports: $Exports<'validator/lib/isIdentityCard'>;
}
declare module 'validator/lib/isIn.js' {
  declare module.exports: $Exports<'validator/lib/isIn'>;
}
declare module 'validator/lib/isInt.js' {
  declare module.exports: $Exports<'validator/lib/isInt'>;
}
declare module 'validator/lib/isIP.js' {
  declare module.exports: $Exports<'validator/lib/isIP'>;
}
declare module 'validator/lib/isIPRange.js' {
  declare module.exports: $Exports<'validator/lib/isIPRange'>;
}
declare module 'validator/lib/isISBN.js' {
  declare module.exports: $Exports<'validator/lib/isISBN'>;
}
declare module 'validator/lib/isISIN.js' {
  declare module.exports: $Exports<'validator/lib/isISIN'>;
}
declare module 'validator/lib/isISO31661Alpha2.js' {
  declare module.exports: $Exports<'validator/lib/isISO31661Alpha2'>;
}
declare module 'validator/lib/isISO31661Alpha3.js' {
  declare module.exports: $Exports<'validator/lib/isISO31661Alpha3'>;
}
declare module 'validator/lib/isISO8601.js' {
  declare module.exports: $Exports<'validator/lib/isISO8601'>;
}
declare module 'validator/lib/isISRC.js' {
  declare module.exports: $Exports<'validator/lib/isISRC'>;
}
declare module 'validator/lib/isISSN.js' {
  declare module.exports: $Exports<'validator/lib/isISSN'>;
}
declare module 'validator/lib/isJSON.js' {
  declare module.exports: $Exports<'validator/lib/isJSON'>;
}
declare module 'validator/lib/isJWT.js' {
  declare module.exports: $Exports<'validator/lib/isJWT'>;
}
declare module 'validator/lib/isLatLong.js' {
  declare module.exports: $Exports<'validator/lib/isLatLong'>;
}
declare module 'validator/lib/isLength.js' {
  declare module.exports: $Exports<'validator/lib/isLength'>;
}
declare module 'validator/lib/isLowercase.js' {
  declare module.exports: $Exports<'validator/lib/isLowercase'>;
}
declare module 'validator/lib/isMACAddress.js' {
  declare module.exports: $Exports<'validator/lib/isMACAddress'>;
}
declare module 'validator/lib/isMagnetURI.js' {
  declare module.exports: $Exports<'validator/lib/isMagnetURI'>;
}
declare module 'validator/lib/isMD5.js' {
  declare module.exports: $Exports<'validator/lib/isMD5'>;
}
declare module 'validator/lib/isMimeType.js' {
  declare module.exports: $Exports<'validator/lib/isMimeType'>;
}
declare module 'validator/lib/isMobilePhone.js' {
  declare module.exports: $Exports<'validator/lib/isMobilePhone'>;
}
declare module 'validator/lib/isMongoId.js' {
  declare module.exports: $Exports<'validator/lib/isMongoId'>;
}
declare module 'validator/lib/isMultibyte.js' {
  declare module.exports: $Exports<'validator/lib/isMultibyte'>;
}
declare module 'validator/lib/isNumeric.js' {
  declare module.exports: $Exports<'validator/lib/isNumeric'>;
}
declare module 'validator/lib/isOctal.js' {
  declare module.exports: $Exports<'validator/lib/isOctal'>;
}
declare module 'validator/lib/isPort.js' {
  declare module.exports: $Exports<'validator/lib/isPort'>;
}
declare module 'validator/lib/isPostalCode.js' {
  declare module.exports: $Exports<'validator/lib/isPostalCode'>;
}
declare module 'validator/lib/isRFC3339.js' {
  declare module.exports: $Exports<'validator/lib/isRFC3339'>;
}
declare module 'validator/lib/isSlug.js' {
  declare module.exports: $Exports<'validator/lib/isSlug'>;
}
declare module 'validator/lib/isSurrogatePair.js' {
  declare module.exports: $Exports<'validator/lib/isSurrogatePair'>;
}
declare module 'validator/lib/isUppercase.js' {
  declare module.exports: $Exports<'validator/lib/isUppercase'>;
}
declare module 'validator/lib/isURL.js' {
  declare module.exports: $Exports<'validator/lib/isURL'>;
}
declare module 'validator/lib/isUUID.js' {
  declare module.exports: $Exports<'validator/lib/isUUID'>;
}
declare module 'validator/lib/isVariableWidth.js' {
  declare module.exports: $Exports<'validator/lib/isVariableWidth'>;
}
declare module 'validator/lib/isWhitelisted.js' {
  declare module.exports: $Exports<'validator/lib/isWhitelisted'>;
}
declare module 'validator/lib/ltrim.js' {
  declare module.exports: $Exports<'validator/lib/ltrim'>;
}
declare module 'validator/lib/matches.js' {
  declare module.exports: $Exports<'validator/lib/matches'>;
}
declare module 'validator/lib/normalizeEmail.js' {
  declare module.exports: $Exports<'validator/lib/normalizeEmail'>;
}
declare module 'validator/lib/rtrim.js' {
  declare module.exports: $Exports<'validator/lib/rtrim'>;
}
declare module 'validator/lib/stripLow.js' {
  declare module.exports: $Exports<'validator/lib/stripLow'>;
}
declare module 'validator/lib/toBoolean.js' {
  declare module.exports: $Exports<'validator/lib/toBoolean'>;
}
declare module 'validator/lib/toDate.js' {
  declare module.exports: $Exports<'validator/lib/toDate'>;
}
declare module 'validator/lib/toFloat.js' {
  declare module.exports: $Exports<'validator/lib/toFloat'>;
}
declare module 'validator/lib/toInt.js' {
  declare module.exports: $Exports<'validator/lib/toInt'>;
}
declare module 'validator/lib/trim.js' {
  declare module.exports: $Exports<'validator/lib/trim'>;
}
declare module 'validator/lib/unescape.js' {
  declare module.exports: $Exports<'validator/lib/unescape'>;
}
declare module 'validator/lib/util/assertString.js' {
  declare module.exports: $Exports<'validator/lib/util/assertString'>;
}
declare module 'validator/lib/util/includes.js' {
  declare module.exports: $Exports<'validator/lib/util/includes'>;
}
declare module 'validator/lib/util/merge.js' {
  declare module.exports: $Exports<'validator/lib/util/merge'>;
}
declare module 'validator/lib/util/toString.js' {
  declare module.exports: $Exports<'validator/lib/util/toString'>;
}
declare module 'validator/lib/whitelist.js' {
  declare module.exports: $Exports<'validator/lib/whitelist'>;
}
declare module 'validator/validator.js' {
  declare module.exports: $Exports<'validator/validator'>;
}
declare module 'validator/validator.min.js' {
  declare module.exports: $Exports<'validator/validator.min'>;
}
