bases:
  - ../../../agent
patchesStrategicMerge:
  - ./agent.yaml
secretGenerator:
  - name: kubesail-agent
    envs:
      - secrets/env.plain
    options:
      disableNameSuffixHash: true
  - name: self-signed
    files:
      - tls.crt=secrets/tls.crt
      - tls.key=secrets/tls.key
    type: 'kubernetes.io/tls'
