apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesail-gateway
spec:
  template:
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        # - name: kubesail-gateway-test
        #   image: kubesail/test:latest
        #   imagePullPolicy: Never
        #   command: ["/app/bin/test-gateway"]
        #   env:
        #     - name: GET_HOSTS_FROM
        #       value: dns
        #     - name: LOG_LEVEL
        #       value: debug
        #     - name: NODE_ENV
        #       value: development
        - name: kubesail-gateway
          image: kubesail/agent
          imagePullPolicy: IfNotPresent
          ports:
            - name: inspector
              containerPort: 9229
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: LOG_LEVEL
              value: debug
            - name: NODE_ENV
              value: development
            - name: APP_ENV
              value: dev
            - name: KUBESAIL_API_TARGET
              value: api
            - name: ALWAYS_VALID_DOMAINS
              value: test-endpoint.example.com
          volumeMounts:
            - name: self-signed
              mountPath: /app/secrets
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: "2"
              memory: 1500Mi
      volumes:
        - name: self-signed
          secret:
            secretName: self-signed
