bases:
  - ../../../gateway
resources:
  # - ./nginx-ingress.yaml
  - ./redis.yaml
  - ./services/metrics.yaml
patchesStrategicMerge:
  - ./gateway.yaml
secretGenerator:
  - name: self-signed
    files:
      - tls.crt=secrets/tls.crt
      - tls.key=secrets/tls.key
    type: "kubernetes.io/tls"
