apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubesail-gateway
spec:
  selector:
    matchLabels:
      app: kubesail-gateway
      tier: service
  minReadySeconds: 0
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      annotations:
        prometheus.io/port: "5000"
        prometheus.io/scrape: "true"
      labels:
        app: kubesail-gateway
        tier: service
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: kubesail-gateway
          image: kubesail/gateway:latest
          imagePullPolicy: IfNotPresent
          command: ["/app/bin/kubesail-gateway"]
          ports:
            - name: metrics
              containerPort: 5000
            - name: gateway-agents
              containerPort: 8000
            - name: gateway-http
              containerPort: 8080
            - name: gateway-https
              containerPort: 8443
          env:
            - name: GET_HOSTS_FROM
              value: dns
            - name: LOG_LEVEL
              value: debug
            - name: LOGGING_LABEL
              value: kubesail-gateway
            - name: NODE_ENV
              value: development
            - name: GATEWAY_INTERNAL_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: "2"
              memory: 1500Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kubesail-gateway
spec:
  type: NodePort
  ports:
    - name: gateway-agents
      port: 8000
      protocol: TCP
      targetPort: gateway-agents
    - name: gateway-http
      port: 8080
      protocol: TCP
      targetPort: gateway-http
    - name: gateway-https
      port: 8443
      protocol: TCP
      targetPort: gateway-https
  selector:
    app: kubesail-gateway
